refs #39908 Add new API
DOM-Digital-Online-Media/living_spaces pull request #147
Opened 2023-07-07 13:42 UTC by victor-aston

2023-07-13 11:29 UTC, boddy-devbranch approved these changes

2023-07-17 09:19 UTC, andrew-sereda requested changes

2023-07-17 09:19 UTC, andrew-sereda commented on modules/living_spaces_activity/js/living_spaces_activity_load.js
> +  };
We should not use set interval here. We should be using nodejs for this as we used it to update notifications bell and dropdown in Drupal.Nodejs.callbacks.livingSpacesActivity

2023-07-19 09:32 UTC, andrew-sereda approved these changes

2023-07-19 09:32 UTC, merged