Ref #45916 implement the "collapsible_menu" hook that add menu items dynamically.
DOM-Digital-Online-Media/living_spaces pull request #169
Opened 2023-07-31 13:33 UTC by ShamryloMykola

2023-08-01 11:43 UTC, victor-aston approved these changes

2023-08-02 08:54 UTC, andrew-sereda requested changes

2023-08-02 08:54 UTC, andrew-sereda commented on modules/living_spaces_default/living_spaces_default.module
> +}
This is obsolete. It is handled in living_spaces_default_query_entity_query_alter

2023-08-02 12:04 UTC, ShamryloMykola commented on modules/living_spaces_default/living_spaces_default.module
> +}
Done.

2023-08-02 13:53 UTC, andrew-sereda approved these changes

2023-08-02 13:53 UTC, merged