refs #48410 Fix validation
DOM-Digital-Online-Media/living_spaces pull request #186
Opened 2023-08-23 09:45 UTC by victor-aston

2023-08-23 14:33 UTC, andrew-sereda requested changes

2023-08-23 14:33 UTC, andrew-sereda commented on modules/living_spaces_activity/living_spaces_activity.tokens.inc
>            $replacements[$original] = t('You were');
In this case behaviour is wrong. 
When message from deleted user it would write "You were" which is not true. I suggest to write "Deleted employee was" if message author does not exist.
Please note that we already have translation for "Deleted employee", so use that, not "Deleted employee was"

2023-08-23 14:41 UTC, victor-aston commented on modules/living_spaces_activity/living_spaces_activity.tokens.inc
>            $replacements[$original] = t('You were');
done.

2023-08-24 11:31 UTC, andrew-sereda requested changes

2023-08-24 11:31 UTC, andrew-sereda commented on modules/living_spaces_activity/living_spaces_activity.tokens.inc
> +          $replacements[$original] = t('Deleted employee') . ' ' . t('was');
if `$message->getOwnerId() == \Drupal::currentUser()->id()` the $replacements[$original] from 46 line will be replaced with this one which would not be correct.

2023-08-24 11:44 UTC, victor-aston commented on modules/living_spaces_activity/living_spaces_activity.tokens.inc
> +          $replacements[$original] = t('Deleted employee') . ' ' . t('was');
fixed.

2023-08-24 12:17 UTC, andrew-sereda approved these changes

2023-08-24 12:17 UTC, merged