refs #49203 Add CkEditor plugins
DOM-Digital-Online-Media/living_spaces pull request #229
Opened 2023-10-02 09:11 UTC by victor-aston

2023-10-02 16:12 UTC, boddy-devbranch approved these changes

2023-10-03 09:56 UTC, andrew-sereda requested changes

2023-10-03 09:56 UTC, andrew-sereda commented on config/optional/linkit.linkit_profile.default.yml
> +uuid: aa0dddc0-45e3-4ab3-8e99-eb5096981ad3
Install configs should not contain uuid

2023-10-03 09:56 UTC, andrew-sereda commented on config/optional/linkit.linkit_profile.default.yml
> +  default_config_hash: 0Jw_BFJCCtWk187tIYvME58VFpYwPaAdrc4eRtAyHH0
This is also should be removed

2023-10-03 09:58 UTC, victor-aston commented on config/optional/linkit.linkit_profile.default.yml
> +uuid: aa0dddc0-45e3-4ab3-8e99-eb5096981ad3
done,

2023-10-03 09:58 UTC, victor-aston commented on config/optional/linkit.linkit_profile.default.yml
> +  default_config_hash: 0Jw_BFJCCtWk187tIYvME58VFpYwPaAdrc4eRtAyHH0
done.

2023-10-03 10:24 UTC, andrew-sereda approved these changes

2023-10-03 10:25 UTC, merged