Ref #42068 Hide 'preferred_spaces' field on create employee form. Fix…
DOM-Digital-Online-Media/living_spaces pull request #52
Opened 2023-01-04 17:24 UTC by boddy-devbranch

…ed options of available roles for current user.

2023-01-19 11:09 UTC, andrew-sereda approved these changes

2023-01-19 11:11 UTC, andrew-sereda requested changes

2023-01-19 11:11 UTC, andrew-sereda commented on modules/living_spaces_intranet/living_spaces_intranet.module
> +  if (isset($form['account']['roles']['#options']) && \Drupal::hasService('delegatable_roles')) {
You have not added module with this service to composer.json in profile

2023-02-21 07:52 UTC, victor-aston commented on config/install/core.entity_form_display.user.user.employee.yml
> +  default_config_hash: _W4c-Pjk06XeQX4Q-UnsEoLwAfSygIDBGiUiPz1LJIg
no need to add that info.

2023-02-21 07:53 UTC, victor-aston commented on modules/living_spaces_intranet/living_spaces_intranet.module
> +  if (isset($form['account']['roles']['#options']) && \Drupal::hasService('delegatable_roles')) {
you should add the module as a dependency to the module and remove `\Drupal::hasService()` validation.

2023-02-21 07:54 UTC, victor-aston commented on modules/living_spaces_intranet/living_spaces_intranet.module
> +    $form['account']['roles']['#options'] = array_intersect($form['account']['roles']['#options'], $assignableRoles);
please, use `$assignable_roles` instead of `$assignableRoles`

2023-02-21 07:55 UTC, victor-aston requested changes
please, fix some small issues

2023-02-27 10:46 UTC, victor-aston approved these changes

2023-02-27 12:32 UTC, andrew-sereda approved these changes

2023-02-27 12:33 UTC, merged